feat(envited.ascs.digital): Replace du
ASCS-eV/envited-x-data-space pull request #364
Opened 2024-11-05 07:56 UTC by jeroenbranje

mmy Assets

2024-11-05 17:19 UTC, jdsika commented
Contact sales is handing out the wrong asset URL

2024-11-07 13:26 UTC, royscheeren requested changes

2024-11-07 13:26 UTC, royscheeren commented on apps/envited.ascs.digital/app/assets/[id]/page.tsx
> +export const dynamic = 'force-dynamic'
Because you're using a url param, we should not need the dynamic directive.

2024-11-07 13:26 UTC, royscheeren commented on apps/envited.ascs.digital/app/community/[slug]/page.tsx
> +  const tokens = await getTokensByProfileSlug(slug)
Is it worth looking at a getProfileWithTokens query?

2024-11-07 13:26 UTC, royscheeren commented on apps/envited.ascs.digital/common/database/queries/tokens.ts
> +export const getTokenAttributesById = (db: DatabaseConnection) => async (id: string) =>
Can we try the relation again?

2024-11-07 13:26 UTC, royscheeren commented on apps/envited.ascs.digital/app/dashboard/assets/page.tsx
> +  const tokens = await getTokensByIssuerId()
I don't really like calling functions `byId` without actually providing an id. I assume its coming from the the session later, but reading the function name makes it look like something is missing.

Something like getUsersIssuersTokens() (can use some improvement) describes better what actually happens.

2024-11-09 13:12 UTC, royscheeren approved these changes

2024-11-09 13:12 UTC, merged