feat: handle asset data from zip
ASCS-eV/envited-x-data-space pull request #374
Opened 2024-11-12 13:55 UTC by jeroenbranje

# Work done
Handle assets after upload

Steps

- [x] Open asset.zip
- [x] Validate manifest.json
- [x] Locate all content referenced in manifest.json (file name is static)
- [x] Locate domainMetadata.json (name according to manifest.json)
- [x] Validate domainMetadata.json
- [x] If all green, offer upload
- [x] Calculate CID of asset.zip -> rename and store in bucket: https://assets.envited-x.net/Asset-CID
- [x] Create copy of manifest.json named tzip21_asset_manifest.json for replacing relative paths with URLs
- [x] Upload "publicUser" information to IPFS -> links in tzip21_asset_manifest.json
- [x] Store "registeredUser" information in bucket: https://metadata.envited-x.net/Asset-CID -> links in tzip21_asset_manifest.json
- [x] Create tzip21_token_metadata.json -> fill information according to mapping table
- [x] Make sure to use unique attributes as in this [PR](https://github.com/ASCS-eV/smart-contracts/pull/9)

Closes #336, #332, #278, #172, #362

2024-11-14 09:03 UTC, royscheeren requested changes
The fact that you split things up in small utility functions that are easy to test is really nice, only advice would be to really think about your naming, does my function name really describe what im doing etc etc.

2024-11-14 09:03 UTC, royscheeren commented on apps/envited.ascs.digital/common/asset/validateAndCreateMetadata.ts
> +    getFilesWithPathAndByteArrayFromManifest: (byteArray: Uint8Array, manifest: Manifest) => any
Is it not possible to type the return types on line 206 and 207?

2024-11-14 09:03 UTC, royscheeren commented on apps/envited.ascs.digital/common/asset/validateAndCreateMetadata.ts
> +    getFilesWithPathAndByteArrayFromManifest: (byteArray: Uint8Array, manifest: Manifest) => any
So the main question I have here is the name of the variable byteArray. In general that should mean I could throw in any byteArray and I'd get a result. Ie some utility function on a filetype. (Example on line 206, presumably if you throw it any byteArray with a filename will give you the expected result)

In this case however I suspect it has to be more specific because there is a second parameter called manifest. So I wonder if it would be better if the word byteArray would be more specific to what it needs to be and the type Uint8Array will be clear enough to expect what type of parameter it will be. (This might go further than just this function)

2024-11-14 09:03 UTC, royscheeren commented on apps/envited.ascs.digital/common/asset/validateAndCreateMetadata.utils.test.ts
> +  describe('formatManifestLinkPath', () => {
this description is not the function you are testing

2024-11-14 09:03 UTC, royscheeren commented on apps/envited.ascs.digital/common/asset/validateAndCreateMetadata.utils.test.ts
> +  describe('formatManifestLinkPath', () => {
this description is not the function you are testing

2024-11-14 09:03 UTC, royscheeren commented on apps/envited.ascs.digital/common/asset/validateAndCreateMetadata.utils.test.ts
> +  describe('getAllManifestLinks', () => {
this description is not the function you are testing

2024-11-14 09:03 UTC, royscheeren commented on apps/envited.ascs.digital/common/asset/validateAndCreateMetadata.utils.ts
> +    owner: getPathsOfManifestFiles(propOr([], 'owner')(files)),
Here I wonder if this function should run if theres an empty array? I assume the result will be an empty array again. Maybe a ternary is a better option here.

2024-11-14 09:03 UTC, royscheeren commented on apps/envited.ascs.digital/common/asset/validateAndCreateMetadata.utils.ts
> +  return [...assetData, ...contentData]
nice

2024-11-14 09:03 UTC, royscheeren commented on apps/envited.ascs.digital/common/asset/validateAndCreateMetadata.utils.ts
> +export const _getFileWithPathAndBuffer =
Are you actually getting a file here, or "just" a path and a buffer?

2024-11-14 09:03 UTC, royscheeren commented on apps/envited.ascs.digital/common/aws/handlers/processAssetUpload/processAssetUpload.ts
> +      console.log('validateAndCreateMetadata - files', files)
Wanna keep this one or should it go?

2024-11-29 10:56 UTC, jdsika commented
1) Processing does not "finish" by itself. I have to refresh the page
2) mint does not work. I get the request to connect and then not the request to sign a transaction.
3) If i click mint again then it want to connect again (which it did already before)

2024-12-02 09:41 UTC, royscheeren commented
> 1. Processing does not "finish" by itself. I have to refresh the page
> 2. mint does not work. I get the request to connect and then not the request to sign a transaction.
> 3. If i click mint again then it want to connect again (which it did already before)
> 4. Altme asks me also twice to connect. The first request is then "overwritten" by the second

1: #384 
2: Was a permissions issue with pinata, should be solved now
3: Known issue: #385

2024-12-03 10:46 UTC, royscheeren submitted a review, later dismissed

2024-12-03 10:46 UTC, royscheeren commented on apps/envited.ascs.digital/common/asset/validateAndCreateMetadata.test.ts
> +        })(byteArray as any, manifest as any)
Can these anys be specified?

2024-12-03 10:46 UTC, royscheeren commented on apps/envited.ascs.digital/common/asset/types.ts
> +  '@context': any
Does this need to be an any?

2024-12-03 10:46 UTC, royscheeren commented on apps/envited.ascs.digital/common/asset/validateAndCreateMetadata.ts
>      ) => Promise<{ conforms: boolean; reports: (ValidationReport<any> | { conforms: boolean })[]; data: any }>
Can this any be specified?

2024-12-03 11:06 UTC, jeroenbranje commented on apps/envited.ascs.digital/common/asset/validateAndCreateMetadata.test.ts
> +        })(byteArray as any, manifest as any)
byteArray not because we send a string and check the other functions with this string

2024-12-03 11:18 UTC, royscheeren approved these changes

2024-12-03 11:19 UTC, merged