feat: Add tag NFT token metadata restricted assets
ASCS-eV/envited-x-data-space pull request #396
Opened 2024-12-09 01:10 UTC by jeroenbranje

# Work done
Add check for external links in manifest

Closes #382

2024-12-10 08:18 UTC, royscheeren requested changes

2024-12-10 08:18 UTC, royscheeren commented on apps/envited.ascs.digital/common/asset/createTokenMetadata.test.ts
> +        tags: ['GaiaX', 'ASCS', 'ENVITED-X', 'EVES', 'nft', 'ASAM OpenDRIVE 1.6', 'containsAccessRestrictedLinks'],
Can you create a constant for this? (And subsequently the function names)

2024-12-10 19:56 UTC, jdsika approved these changes

2024-12-13 07:46 UTC, royscheeren approved these changes

2024-12-13 08:52 UTC, merged